# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "gravatar"
name = "Gravatar"
url = "https://gravatar.com/realwilliamwei"

[social.params]
icon = "brand-gravatar"

[[social]]
identifier = "lit.link"
name = "lit.link"
url = "https://lit.link/zh-tw/williamwei"

[social.params]
icon = "lit"
